//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class administration_staff
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public administration_staff()
        {
            this.admin_student = new HashSet<admin_student>();
        }
    
        public int administration_staff_ID { get; set; }
        public string administration_staff_name { get; set; }
        public string administration_staff_national_ID { get; set; }
        public string administration_staff_password { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<admin_student> admin_student { get; set; }
    }
}
