//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Student_Affairs_SystemEntities1 : DbContext
    {
        public Student_Affairs_SystemEntities1()
            : base("name=Student_Affairs_SystemEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admin_student> admin_student { get; set; }
        public virtual DbSet<administration_staff> administration_staff { get; set; }
        public virtual DbSet<course> courses { get; set; }
        public virtual DbSet<prequest_course> prequest_course { get; set; }
        public virtual DbSet<student> students { get; set; }
        public virtual DbSet<student_available_course> student_available_course { get; set; }
        public virtual DbSet<student_case_report> student_case_report { get; set; }
        public virtual DbSet<student_degree> student_degree { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
