//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class prequest_course
    {
        public int ID { get; set; }
        public string pre_ID { get; set; }
        public string course_ID { get; set; }
    
        public virtual course course { get; set; }
        public virtual course course1 { get; set; }
    }
}
