//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public student()
        {
            this.admin_student = new HashSet<admin_student>();
            this.student_available_course = new HashSet<student_available_course>();
            this.student_case_report = new HashSet<student_case_report>();
            this.student_degree = new HashSet<student_degree>();
        }
    
        public string student_ID { get; set; }
        public string student_name { get; set; }
        public string student_national_ID { get; set; }
        public int student_level { get; set; }
        public int student_age { get; set; }
        public string student_phone { get; set; }
        public string student_adress { get; set; }
        public string student_email { get; set; }
        public Nullable<int> student_term { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<admin_student> admin_student { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<student_available_course> student_available_course { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<student_case_report> student_case_report { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<student_degree> student_degree { get; set; }
    }
}
